spring:
  profiles:
    active: development
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    database: default

application:
  message: Training Spring Day One Model

logging:
  level:
    .: info
    com:
      zaxxer:
        hikari:
          HikariConfig:
            .: info
    org:
      springframework:
        transaction:
          interceptor: trace
      hibernate:
        SQL: info
        type:
          .: info
          descriptor:
            sql: trace
    id:
      myindo:
        .: trace
server:
  port: 33333

---

spring:
  profiles: production

---

spring:
  profiles: staging

---

spring:
  profiles: development


